# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 13:59
from __future__ import unicode_literals

import base.notes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.PositiveSmallIntegerField(choices=[(0, 'Prévue'), (1, 'Notation en attente'), (2, 'Notée'), (3, 'Relevée'), (4, 'Annulée')], verbose_name='état')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='ColleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaire', models.DateTimeField()),
                ('salle', models.CharField(max_length=30)),
                ('actif', models.BooleanField()),
                ('colle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colles.Colle')),
                ('colleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Professeur')),
                ('eleves', models.ManyToManyField(blank=True, to='base.Etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='ColleNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', base.notes.NoteField()),
                ('horaire', models.DateTimeField()),
                ('colle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colles.Colle')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='ColleReleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colles', models.ManyToManyField(blank=True, to='colles.Colle')),
            ],
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveSmallIntegerField(choices=[(1, 'lundi'), (2, 'mardi'), (3, 'mercredi'), (4, 'jeudi'), (5, 'vendredi'), (6, 'samedi'), (7, 'dimanche')])),
                ('debut', models.TimeField(verbose_name='début')),
                ('fin', models.TimeField()),
                ('salle', models.CharField(blank=True, max_length=30)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Classe')),
                ('colleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Professeur')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Matiere', verbose_name='matière')),
            ],
            options={
                'verbose_name': 'créneau',
                'ordering': ['jour', 'debut', 'matiere'],
                'verbose_name_plural': 'créneaux',
            },
        ),
        migrations.CreateModel(
            name='Roulement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='RoulementGraine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RoulementLigne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField()),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colles.Creneau')),
                ('roulement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='colles.Roulement')),
            ],
        ),
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField(verbose_name='début')),
                ('fin', models.DateField()),
                ('numero', models.TextField(verbose_name='numéro')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Classe')),
            ],
            options={
                'ordering': ['debut'],
            },
        ),
        migrations.CreateModel(
            name='Trinome',
            fields=[
                ('groupe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Groupe')),
                ('commentaire', models.TextField(blank=True)),
                ('dans_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trinomes', to='base.Classe', verbose_name='classe')),
            ],
            bases=('base.groupe',),
        ),
        migrations.AddField(
            model_name='roulementgraine',
            name='trinomes',
            field=models.ManyToManyField(to='colles.Trinome'),
        ),
        migrations.AddField(
            model_name='roulement',
            name='semaines',
            field=models.ManyToManyField(blank=True, to='colles.Semaine'),
        ),
        migrations.AddField(
            model_name='colledetails',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Groupe'),
        ),
        migrations.AddField(
            model_name='colledetails',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Matiere'),
        ),
        migrations.AddField(
            model_name='colle',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colles.Creneau'),
        ),
    ]
