# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaire', models.DateTimeField()),
                ('etat', models.PositiveSmallIntegerField(choices=[(0, 'Prévue'), (1, 'Notation en attente'), (2, 'Notée'), (3, 'Relevée'), (4, 'Annulée')], verbose_name='État')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Classe')),
                ('colleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Professeur')),
            ],
        ),
        migrations.CreateModel(
            name='ColleNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.SmallIntegerField()),
                ('horaire', models.DateField()),
                ('colle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colles.Colle')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='ColleReleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colles', models.ManyToManyField(to='colles.Colle')),
            ],
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveSmallIntegerField(choices=[(1, 'lundi'), (2, 'mardi'), (3, 'mercredi'), (4, 'jeudi'), (5, 'vendredi'), (6, 'samedi'), (7, 'dimanche')])),
                ('debut', models.TimeField()),
                ('fin', models.TimeField()),
                ('salle', models.CharField(max_length=30)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Classe')),
                ('colleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Professeur')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Matiere')),
            ],
            options={
                'verbose_name_plural': 'créneaux',
                'ordering': ['jour', 'debut', 'matiere'],
                'verbose_name': 'créneau',
            },
        ),
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('numero', models.TextField(verbose_name='Numéro')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Classe')),
            ],
            options={
                'ordering': ['debut'],
            },
        ),
        migrations.AddField(
            model_name='colle',
            name='creneau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colles.Creneau'),
        ),
        migrations.AddField(
            model_name='colle',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Matiere'),
        ),
    ]
