# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaire', models.DateTimeField()),
                ('etat', models.PositiveSmallIntegerField(choices=[(0, b'Pr\xc3\xa9vue'), (1, b'Notation en attente'), (2, b'Not\xc3\xa9e'), (3, b'Relev\xc3\xa9e'), (4, b'Annul\xc3\xa9e')], verbose_name=b'\xc3\x89tat')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Classe')),
                ('colleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Professeur')),
            ],
        ),
        migrations.CreateModel(
            name='ColleNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.SmallIntegerField()),
                ('horaire', models.DateField()),
                ('colle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colles.Colle')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='ColleReleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colles', models.ManyToManyField(to='colles.Colle')),
            ],
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveSmallIntegerField(choices=[(1, b'lundi'), (2, b'mardi'), (3, b'mercredi'), (4, b'jeudi'), (5, b'vendredi'), (6, b'samedi'), (7, b'dimanche')])),
                ('debut', models.TimeField()),
                ('fin', models.TimeField()),
                ('salle', models.CharField(max_length=30)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Classe')),
                ('colleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Professeur')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Matiere')),
            ],
            options={
                'ordering': ['jour', 'debut', 'matiere'],
            },
        ),
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('numero', models.TextField(verbose_name=b'Num\xc3\xa9ro')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Classe')),
            ],
            options={
                'ordering': ['debut'],
            },
        ),
        migrations.AddField(
            model_name='colle',
            name='creneau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colles.Creneau'),
        ),
        migrations.AddField(
            model_name='colle',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Matiere'),
        ),
    ]
