# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_vacances'),
        ('colles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollesParMatiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.PositiveSmallIntegerField(verbose_name='durée hebdomadaire')),
                ('enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Enseignement')),
            ],
        ),
        migrations.CreateModel(
            name='CollesReglages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeros_auto', models.BooleanField(default=False)),
                ('numeros_format', models.CharField(blank=True, max_length=100)),
                ('classe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Classe')),
                ('durees', models.ManyToManyField(through='colles.CollesParMatiere', to='base.Enseignement')),
            ],
        ),
        migrations.AddField(
            model_name='collesparmatiere',
            name='reglages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colles.CollesReglages'),
        ),
        migrations.AlterUniqueTogether(
            name='collesreglages',
            unique_together=set([('classe',)]),
        ),
    ]
