# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colle',
            name='etat',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Prévue'), (1, 'Notation en attente'), (2, 'Notée'), (3, 'Relevée'), (4, 'Annulée')], verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='semaine',
            name='debut',
            field=models.DateField(verbose_name='début'),
        ),
        migrations.AlterField(
            model_name='semaine',
            name='numero',
            field=models.TextField(verbose_name='numéro'),
        ),
    ]
