# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170820_1605'),
        ('colles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colledetails',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='colledetails',
            name='matiere',
        ),
        migrations.AddField(
            model_name='colle',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.Groupe'),
        ),
        migrations.AddField(
            model_name='colle',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Matiere', verbose_name='matière'),
        ),
        migrations.AlterField(
            model_name='colle',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colles.Creneau', verbose_name='créneau'),
        ),
        migrations.AlterField(
            model_name='colle',
            name='etat',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Prévue'), (1, 'Notation en attente'), (2, 'Notée'), (3, 'Relevée'), (4, 'Annulée')], default=0, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='colledetails',
            name='eleves',
            field=models.ManyToManyField(blank=True, to='base.Etudiant', verbose_name='élèves'),
        ),
    ]
