# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170725_1610'),
        ('colles', '0002_auto_20170725_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roulement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Classe')),
                ('semaines', models.ManyToManyField(to='colles.Semaine')),
            ],
        ),
        migrations.CreateModel(
            name='RoulementLigne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='creneau',
            name='colleur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Professeur'),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Matiere'),
        ),
        migrations.AddField(
            model_name='roulementligne',
            name='creneau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colles.Creneau'),
        ),
        migrations.AddField(
            model_name='roulementligne',
            name='roulement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='colles.Roulement'),
        ),
    ]
