# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 13:18
from __future__ import unicode_literals

import base.notes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170803_1518'),
        ('colles', '0003_auto_20170728_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaire', models.DateTimeField()),
                ('salle', models.CharField(max_length=30)),
                ('actif', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RoulementGraine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trinome',
            fields=[
                ('groupe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Groupe')),
                ('commentaire', models.TextField(blank=True)),
                ('dans_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trinomes', to='base.Classe', verbose_name='classe')),
            ],
            bases=('base.groupe',),
        ),
        migrations.RemoveField(
            model_name='colle',
            name='colleur',
        ),
        migrations.RemoveField(
            model_name='colle',
            name='horaire',
        ),
        migrations.RemoveField(
            model_name='colle',
            name='matiere',
        ),
        migrations.AlterField(
            model_name='colle',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colles.Creneau'),
        ),
        migrations.AlterField(
            model_name='collenote',
            name='horaire',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='collenote',
            name='note',
            field=base.notes.NoteField(),
        ),
        migrations.AlterField(
            model_name='collereleve',
            name='colles',
            field=models.ManyToManyField(blank=True, to='colles.Colle'),
        ),
        migrations.AlterField(
            model_name='roulement',
            name='semaines',
            field=models.ManyToManyField(blank=True, to='colles.Semaine'),
        ),
        migrations.AddField(
            model_name='roulementgraine',
            name='trinomes',
            field=models.ManyToManyField(to='colles.Trinome'),
        ),
        migrations.AddField(
            model_name='colledetails',
            name='colle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colles.Colle'),
        ),
        migrations.AddField(
            model_name='colledetails',
            name='colleur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Professeur'),
        ),
        migrations.AddField(
            model_name='colledetails',
            name='eleves',
            field=models.ManyToManyField(blank=True, to='base.Etudiant'),
        ),
        migrations.AddField(
            model_name='colledetails',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Groupe'),
        ),
        migrations.AddField(
            model_name='colledetails',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Matiere'),
        ),
    ]
