# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 14:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academie',
            name='departements',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='départements'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='matieres',
            field=models.ManyToManyField(through='base.Enseignement', to='base.Matiere', verbose_name='matières'),
        ),
        migrations.AlterField(
            model_name='enseignement',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Matiere', verbose_name='matière'),
        ),
        migrations.AlterField(
            model_name='enseignement',
            name='specialite',
            field=models.BooleanField(verbose_name='spécialité'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='academie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Academie', verbose_name='académie'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='adresse',
            field=models.TextField(blank=True, verbose_name="adresse de l'établissement"),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='entree',
            field=models.DateField(blank=True, null=True, verbose_name='entrée'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='etudiants',
            field=models.ManyToManyField(to='base.Etudiant', verbose_name='étudiants'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Etablissement', verbose_name='établissement'),
        ),
    ]
