# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 14:05
from __future__ import unicode_literals

import base.uppercasecharfield
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='numero_uai',
            field=base.uppercasecharfield.Lettre23Field(length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message="Le code doit être constitué de 7 chiffres suivis d'une lettre code", regex='\\d{7,7}[a-zA-Z]'), django.core.validators.RegexValidator(message="Le code doit être constitué de 7 chiffres suivis d'une lettre code", regex='\\d{7,7}[a-zA-Z]'), django.core.validators.RegexValidator(message="Le code doit être constitué de 7 chiffres suivis d'une lettre code", regex='\\d{7,7}[a-zA-Z]')], verbose_name='UAI'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='ine',
            field=base.uppercasecharfield.Lettre23Field(length=11, validators=[django.core.validators.RegexValidator(message="Le code doit être constitué de 10 chiffres suivis d'une lettre code", regex='\\d{10,10}[a-zA-Z]'), django.core.validators.RegexValidator(message="Le code doit être constitué de 10 chiffres suivis d'une lettre code", regex='\\d{10,10}[a-zA-Z]'), django.core.validators.RegexValidator(message="Le code doit être constitué de 10 chiffres suivis d'une lettre code", regex='\\d{10,10}[a-zA-Z]')], verbose_name="INE (numéro d'étudiant)"),
        ),
    ]
