# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('debut', models.DateField(verbose_name='début')),
                ('fin', models.DateField()),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Annee')),
            ],
            options={
                'verbose_name_plural': 'vacances',
                'verbose_name': 'vacances',
            },
        ),
    ]
