# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170803_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='virtuelle',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupe',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Annee', verbose_name='année'),
        ),
    ]
