# Generated by Django 2.1 on 2018-08-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'interrogation'), (1, 'travaux dirigés')], default=0, verbose_name="mode d'interrogation"),
        ),
    ]
