# Generated by Django 2.1 on 2018-08-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0003_trinome_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='collesenseignement',
            name='mode_defaut',
            field=models.PositiveSmallIntegerField(choices=[(0, 'interrogation'), (1, 'travaux dirigés')], default=0, verbose_name='mode par défaut'),
        ),
    ]
