# Generated by Django 2.1 on 2018-08-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0003_vacances_type_vacances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academie',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='numéro'),
        ),
    ]
