# Generated by Django 2.1 on 2018-08-26 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0004_collesenseignement_mode_defaut'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trinome',
            unique_together={('annee', 'classe', 'periode', 'nom')},
        ),
    ]
