# Generated by Django 2.1 on 2018-08-19 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0005_longueur_appellation_etablissement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotationClasseLigne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures', models.PositiveIntegerField(verbose_name="nombre d'heures")),
                ('dotation_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pykol.DotationClasse')),
                ('enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pykol.Enseignement')),
            ],
        ),
        migrations.RemoveField(
            model_name='collesenseignement',
            name='enseignement',
        ),
        migrations.AddField(
            model_name='collesenseignement',
            name='enseignements',
            field=models.ManyToManyField(to='pykol.Enseignement'),
        ),
        migrations.AddField(
            model_name='collesenseignement',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
