# Generated by Django 2.1 on 2018-08-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0005_unicite_trinome_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='collesenseignement',
            name='nomenclature_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
