# Generated by Django 2.1 on 2018-08-20 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0006_dotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='collesenseignement',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pykol.Classe'),
            preserve_default=False,
        ),
    ]
