# Generated by Django 2.1 on 2018-08-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0008_groupe_effectif_sts'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeEffectif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectif_sts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pykol.Classe')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pykol.Groupe')),
            ],
        ),
        migrations.AddField(
            model_name='groupe',
            name='classes_appartenance',
            field=models.ManyToManyField(through='pykol.GroupeEffectif', to='pykol.Classe'),
        ),
    ]
