# Generated by Django 2.1 on 2018-08-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0008_deplacer_code_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='old_code_structure',
        ),
        migrations.AlterField(
            model_name='groupe',
            name='code_structure',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='groupe',
            unique_together={('code_structure', 'annee')},
        ),
    ]
