# Generated by Django 2.1 on 2018-08-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0009_groupeeffectif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='professeur',
            name='disciplines',
            field=models.ManyToManyField(to='pykol.Discipline'),
        ),
    ]
