# Generated by Django 2.1 on 2018-08-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0010_disciplines_professeurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filles', to='pykol.Matiere'),
        ),
    ]
