# Generated by Django 2.1 on 2018-08-29 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0011_classe_enseignement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignement',
            name='option',
        ),
        migrations.RemoveField(
            model_name='mefmatiere',
            name='mode_election',
        ),
        migrations.RemoveField(
            model_name='mefmatiere',
            name='rang',
        ),
        migrations.AddField(
            model_name='mefmatiere',
            name='modalite_option',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'tronc commun'), (2, 'obligatoire'), (3, 'facultative')], null=True),
        ),
        migrations.AddField(
            model_name='mefmatiere',
            name='rang_option',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enseignement',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pykol.Groupe'),
        ),
        migrations.AlterField(
            model_name='enseignement',
            name='modalite_option',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'tronc commun'), (2, 'obligatoire'), (3, 'facultative')], null=True),
        ),
        migrations.AlterField(
            model_name='mefmatiere',
            name='matiere',
            field=models.ForeignKey(blank=True, limit_choices_to={'virtuelle': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pykol.Matiere', verbose_name='matière'),
        ),
        migrations.AlterField(
            model_name='optionetudiant',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pykol.Matiere', verbose_name='matière'),
        ),
        migrations.AlterField(
            model_name='optionetudiant',
            name='modalite_option',
            field=models.PositiveSmallIntegerField(choices=[(1, 'tronc commun'), (2, 'obligatoire'), (3, 'facultative')]),
        ),
    ]
