# Generated by Django 2.1 on 2018-08-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0011_matieres_filles'),
    ]

    operations = [
        migrations.AddField(
            model_name='academie',
            name='nom_complet',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
