# Generated by Django 2.1 on 2018-08-24 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0012_academie_nom_complet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creneau',
            options={'verbose_name': 'créneau', 'verbose_name_plural': 'créneaux'},
        ),
        migrations.RemoveField(
            model_name='creneau',
            name='matiere',
        ),
        migrations.AddField(
            model_name='creneau',
            name='enseignement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pykol.Enseignement'),
        ),
    ]
