# Generated by Django 2.1 on 2018-08-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0013_creneau_enseignement'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='colles_ens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pykol.CollesEnseignement'),
        ),
    ]
