# Generated by Django 2.1 on 2018-08-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0013_mefmatiere_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='numero_siecle',
            field=models.CharField(default='', max_length=30, verbose_name='Numéro interne SIECLE'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='etudiant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='ine',
            field=models.CharField(blank=True, max_length=11, unique=True, null=True, verbose_name="INE (numéro d'étudiant)"),
        ),
    ]
