# Generated by Django 2.1 on 2018-10-15 13:26

from django.db import migrations, models
import pykol.models.base.utilisateurs


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0014_numero_siecle'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='id_acad',
            field=models.CharField(blank=True, max_length=20, verbose_name='identifiant académique'),
        ),
    ]
