# Generated by Django 2.1 on 2018-08-24 19:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0015_colle_enseignement'),
    ]

    operations = [
        migrations.AddField(
            model_name='colle',
            name='colles_ens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pykol.CollesEnseignement'),
        ),
        migrations.AddField(
            model_name='creneau',
            name='duree',
            field=models.DurationField(default=datetime.timedelta(0, 3600), verbose_name='durée'),
        ),
        migrations.AlterField(
            model_name='creneau',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'interrogation'), (1, 'travaux dirigés')], default=0, verbose_name='mode de déroulement'),
        ),
    ]
