# Generated by Django 2.1 on 2018-11-11 06:40

from django.db import migrations, models
import pykol.models.base.utilisateurs


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0015_prof_id_acad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collereleveligne',
            name='etat',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nouveau'), (1, 'Payé'), (2, 'Saisie dans ASIE')], default=0, verbose_name='état'),
        ),
    ]
