# Generated by Django 2.1 on 2018-11-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0017_etudiant_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='nom_asie',
            field=models.CharField(blank=True, help_text="Champ à remplir lorsque le nom affiché pour ce professeur ne correspond pas au nom sous lequel il est connu dans ASIE. Ce champ peut être laissé vide si le nom connu dans ASIE n'est pas différent.", max_length=100, verbose_name='Nom du professeur dans ASIE'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='prenom_asie',
            field=models.CharField(blank=True, help_text="Champ à remplir lorsque le prénom affiché pour ce professeur ne correspond pas au prénom sous lequel il est connu dans ASIE. Ce champ peut être laissé vide si le prénom connu dans ASIE n'est pas différent.", max_length=100, verbose_name='Prénom du professeur dans ASIE'),
        ),
    ]
