# Generated by Django 2.1 on 2019-01-15 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0019_user_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeNotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('debut', models.DateField(verbose_name='début')),
                ('fin', models.DateField()),
                ('enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pykol.Enseignement')),
                ('semaines', models.ManyToManyField(to='pykol.Semaine')),
            ],
            options={
                'verbose_name': 'période',
                'verbose_name_plural': 'périodes',
                'abstract': False,
            },
        ),
    ]
