# Generated by Django 2.1 on 2019-02-05 08:00

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0020_periodenotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodenotation',
            name='semaines',
        ),
    ]
