# Generated by Django 2.1 on 2019-05-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0032_durees_decouvert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='decouvert_duree',
            field=models.DurationField(blank=True, help_text="Lorsque le découvert est autorisé sur ce compte, ce champ donne une limite sur le nombre d'heures comptabilisées négativement. Par exemple, si ce champ vaut 3h, le solde du compte devra toujours être supérieur ou égal à -3h.", null=True, verbose_name='durée à découvert autorisée'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='decouvert_duree_interrogation',
            field=models.DurationField(blank=True, null=True, verbose_name="durée d'interrogation à découvert autorisée"),
        ),
    ]
