# Generated by Django 2.2.1 on 2019-06-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0035_colles_duree_interrogation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='compte',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='compte',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
