# Generated by Django 2.2.1 on 2019-07-12 10:06

from datetime import timedelta
from django.db import migrations

def colle_ligne_dotation_init(apps, schema_editor):
	Colle = apps.get_model('pykol', 'Colle')
	MouvementLigne = apps.get_model('pykol', 'MouvementLigne')

	for colle in Colle.all_objects.all():
		colle.ligne_dotation = MouvementLigne.objects.filter(
			mouvement__colle=colle,
			duree__gt=timedelta(),
			).order_by('-pk').first()
		colle.save()

def reverse_colle_ligne_dotation_init(apps, schema_editor):
	Colle = apps.get_model('pykol', 'Colle')

class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0037_colle_ligne_dotation'),
    ]

    operations = [
		migrations.RunPython(colle_ligne_dotation_init,
			reverse_colle_ligne_dotation_init, elidable=True),
    ]
