# Generated by Django 2.2.1 on 2019-07-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0038_colle_init_ligne_dotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colle',
            name='ligne_dotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pykol.MouvementLigne', verbose_name='ligne de dotation'),
        ),
    ]
