# Generated by Django 2.2.1 on 2019-08-30 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0039_colle_ligne_dotation_notnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='compte_professeurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etablissement_professeurs', to='pykol.Compte'),
        ),
    ]
