# Generated by Django 2.2.1 on 2019-08-30 08:23

from django.db import migrations

from django.conf import settings

def init_compte_professeurs(apps, schema_editor):
	Compte = apps.get_model('pykol', 'Compte')
	Etablissement = apps.get_model('pykol', 'Etablissement')
	racine_profs = Compte.objects.get(nom="Professeurs")
	try:
		etablissement = Etablissement.objects.get(pk=settings.PYKOL_UAI_DEFAUT)
		etablissement.compte_professeurs = racine_profs
		etablissement.save()
	except:
		pass

class Migration(migrations.Migration):

	dependencies = [
		('pykol', '0040_etablissement_compte_professeurs'),
	]

	operations = [
		migrations.RunPython(init_compte_professeurs,
			reverse_code=migrations.RunPython.noop, elidable=True),
	]
