# Generated by Django 2.2.1 on 2019-09-01 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0041_init_compte_professeurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBeeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fichier', models.DateField()),
                ('date_import', models.DateField()),
                ('import_type', models.PositiveSmallIntegerField(choices=[(1, 'STS-EDT'), (2, 'base élèves'), (3, 'structures'), (4, 'nomenclatures'), (5, 'dotations en colles'), (6, 'grilles ECTS')])),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pykol.Annee')),
            ],
        ),
    ]
