# Generated by Django 2.2.1 on 2019-09-07 10:18

from django.db import migrations
import pykol.models.base.utilisateurs


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0042_importbeelog'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='professeur',
            managers=[
                ('objects', pykol.models.base.utilisateurs.ProfesseurManager()),
            ],
        ),
    ]
