# Generated by Django 2.2.13 on 2020-10-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pykol', '0046_code_indemnite_ligne_defaut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collereleveligne',
            name='taux',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1è année - 19 étudiants ou moins'), (2, '1è année - Entre 20 et 35 étudiants'), (3, '1è année - À partir de 36 étudiants'), (4, '2è année - 19 étudiants ou moins'), (5, '2è année - Entre 20 et 35 étudiants'), (6, '2è année - À partir de 36 étudiants')], null=True, verbose_name='taux'),
        ),
        migrations.AlterField(
            model_name='mouvementligne',
            name='taux',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1è année - 19 étudiants ou moins'), (2, '1è année - Entre 20 et 35 étudiants'), (3, '1è année - À partir de 36 étudiants'), (4, '2è année - 19 étudiants ou moins'), (5, '2è année - Entre 20 et 35 étudiants'), (6, '2è année - À partir de 36 étudiants')], null=True, verbose_name='taux'),
        ),
    ]
